### ISSUE TITLE
Install fail @21.2

### ISSUE THREAD

**Issue by MarcoCheng** [bsavery/RenderManForBlender#510]
Rib gen error: Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\RenderManForBlender-master\engine.py", line 142, in update
    engine.render_pass.gen_rib(engine=engine)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\RenderManForBlender-master\engine.py", line 788, in gen_rib
    write_rib(self, self.scene, self.ri, visible_objects, engine, do_objects)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\RenderManForBlender-master\export.py", line 3437, in write_rib
    export_display(ri, rpass, scene)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\RenderManForBlender-master\export.py", line 3138, in export_display
    ts = strftime("%a %b %d %H:%M:%S %Z %Y", gmtime())
ValueError: embedded null byte

It gives an error on 21.2 addon, i downloaded plugin on 5,June 2017. Blender:2.78

**Comment by bsavery** [comment]
We are no longer fixing issues with the 21.2 version.  Sorry.

**Comment by bsavery** [comment]
https://bugs.python.org/issue25023  actually this appears to be a python bug.
